vsftpd:
  image: tukiyo3/openwrt-ftpd
  restart: always
  ports:
    - "21:21"
    - "65000-65100:65000-65100"
  volumes:
    - ./vol/:/data/
  environment:
    #- HOST=my.server.com
    - HOST=localhost
    #- HOST=192.168.10.7
