#!/bin/bash

if [ -z $HOST ] ; then
    echo
    echo "ERROR: you MUST specify a host name or an IP, which will be used as the target for PASV command"
    echo
    exit 1
fi

RESOLVE_HOSTNAME=YES

# if HOST is a dotted quad, then it shouldn't be resolved with DNS
if [[ $HOST =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]] ; then
    RESOLVE_HOSTNAME=NO
fi

mkdir -m 0700 -p /var/empty
mkdir -m 0755 -p /var/run

mkdir -m 0755 -p /data
chown root:root /data

userctl() {
    existing=$(grep $FTP_USER /etc/passwd | cut -f 1 -d :)
    
    HOMEDIR=/data/$FTP_USER
    if [ ! -z "$HOME_DIR" ];then
        HOMEDIR=/data/$HOME_DIR
    fi

    if [ "$existing" = "$FTP_USER" ] ; then
        usermod -d $HOMEDIR -s /bin/false -g ftp -p $(openssl passwd $FTP_PASS) $FTP_USER
    else
        useradd -d $HOMEDIR -s /bin/false -g ftp -p $(openssl passwd $FTP_PASS) $FTP_USER
    fi
    
    mkdir -m 0775 -p $HOMEDIR
    chown -R $FTP_USER:ftp $HOMEDIR

    # text_userdb_names
    mkdir -m 0755 -p $HOMEDIR/etc
    cp -a /etc/passwd $HOMEDIR/etc/passwd
    cp -a /etc/group $HOMEDIR/etc/group
    # set timezone
    cp /etc/localtime $HOMEDIR/etc/localtime
}
readline() {
    cat /users.txt | while read line; do
        FTP_USER=`echo $line | awk '{print $1}'`
        FTP_PASS=`echo $line | awk '{print $2}'`
        HOME_DIR=`echo $line | awk '{print $3}'`
        userctl $FTP_USER $FTP_PASS $HOME_DIR
    done;
}
readline

cat <<EOF> /etc/vsftpd.conf

background=NO
listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=000
check_shell=NO
session_support=NO
chroot_local_user=YES
allow_writeable_chroot=yes

pasv_address=$HOST
pasv_addr_resolve=$RESOLVE_HOSTNAME

pasv_min_port=$PASV_MIN_PORT
pasv_max_port=$PASV_MAX_PORT
pasv_enable=YES
pasv_promiscuous=NO

port_enable=YES
port_promiscuous=NO

seccomp_sandbox=NO

log_ftp_protocol=YES
text_userdb_names=YES
EOF

/etc/init.d/vsftpd start
